#!/bin/sh

# Should we offer our services?
[ -f /etc/default/kde-services-sidux ] && . /etc/default/kde-services-sidux

[ "$KDE_SERVICES_ENABLED" = "false" ] && exit 0

# Start krandrtray
if [ -x /usr/bin/krandrtray ]; then
	xrandr -q >/dev/null 2>/dev/null && krandrtray
fi

# Start mixer
if [ -x /usr/bin/kmix ]; then
	# kmix already started?
	if pgrep -x kmix >/dev/null 2>&1 && lsmod | egrep -q "snd|soundcore"; then
		# be sure that kmix just starts in tray!
		if grep -q ^Visible ~/.kde/share/config/kmixrc 2>/dev/null; then
			sed -i 's/^Visible=.*/Visible=false/' ~/.kde/share/config/kmixrc
		else
			echo "Visible=false" > ~/.kde/share/config/kmixrc
		fi
		
		kmix
		
		if [ "$?" -eq 0 ] && [ -x /usr/bin/dcop ]; then
			sleep 2
			# set a sane default volume on Mixers set to 0
			MIXERS=$(dcop kmix | sed -n 's/Mixer\([[:digit:]]\+\)/\1/p')
			if [ -n "$MIXERS" ]; then
				for mixer in $MIXERS; do
					if [ "$(dcop kmix Mixer${mixer} volume ${mixer})" = 0 ]; then
						dcop kmix Mixer${mixer} setMasterVolume 75
					fi
				done
			fi
		fi
	fi
fi

# Start network monitor
if [ -e /usr/share/services/kded/knemod.desktop ]; then
	dcop kded kded loadModule knemod
fi

# Start kpowersave
if [ -x /usr/bin/kpowersave ]; then
	if pidof powersaved >/dev/null || [ "$KDE_SERVICES_LAPTOP" != "false" ]; then
		/usr/bin/kpowersave
		# allow kpowersave to autostart (disabled by default)
		if grep -q ^Autostart ~/.kde/share/config/kpowersaverc 2>/dev/null; then
			sed -i 's/Autostart=.*/Autostart=true/' ~/.kde/share/config/kpowersaverc
		else
			echo "Autostart=true" > ~/.kde/share/config/kpowersaverc
		fi
	fi
fi
