#!/bin/bash

# Should we offer our services?
[ -f /etc/default/kde-services-sidux ] && . /etc/default/kde-services-sidux

[ "$KDE_SERVICES_ENABLED" = "false" ] && exit 0

# Start krandrtray
if [ -x /usr/bin/krandrtray ]; then
	xrandr -q >/dev/null 2>/dev/null && krandrtray
fi

# Start mixer
if [ -x /usr/bin/kmix ]; then
	# kmix already started?
	KMIX_STARTED=""
	PSAX="$(ps ax)"
	case "$PSAX" in *kmix*) KMIX_STARTED="yes" ;; esac
 
	if test -z "$KMIX_STARTED" && lsmod | egrep -q "snd|soundcore"; then
		#
		# be sure that kmix just starts in tray!
		#

		if [ -r $HOME/.kde/share/config/kmixrc ]; then
			perl -pi -e 's/^Visible=.*/Visible=false/' $HOME/.kde/share/config/kmixrc
		else
			echo "Visible=false" > $HOME/.kde/share/config/kmixrc
		fi
		
		kmix
	fi
fi

# Start network monitor
if [ -e /usr/share/services/kded/knemod.desktop ]; then
	dcop kded kded loadModule knemod
fi

# Start kpowersave
if [ -x /usr/bin/kpowersave ]; then
	if pidof powersaved >/dev/null 2>&1 || \
		[ -n "$(perl -le 'print for grep -d, </proc/acpi/battery/*>')" ]; then
		/usr/bin/kpowersave
		if [ -r $HOME/.kde/share/config/kpowersaverc ]; then
			perl -pi -e 's/^AutoStart=.*/AutoStart=true/' \
				$HOME/.kde/share/config/kpowersaverc
		fi
	fi
fi
